"""Layer 2: snippet-quality fixture test.

For each row in tests/fixtures/snippet_quality.jsonl (generated by
evaluation/build_snippet_fixtures.py), fetch the source_url, extract
clean text, run the DIY snippet picker, and assert the returned
chunks contain (a substantial substring of) the historically-accepted
evidence_quote. Aggregate pass rate must be >= 70% across the fixture.

Marked @pytest.mark.live (network + Claude). Skip by default.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

_FIXTURE = Path(__file__).parent / "fixtures" / "snippet_quality.jsonl"


def _load_fixtures():
    if not _FIXTURE.exists():
        return []
    return [json.loads(line) for line in _FIXTURE.read_text(encoding="utf-8").splitlines() if line.strip()]


def _substring_overlap(quote: str, chunk_text: str, min_len: int = 30) -> bool:
    """True if chunk_text contains a substring of quote at least min_len long."""
    if len(quote) < min_len:
        return quote in chunk_text  # short quotes: exact-match
    # Sliding window: any min_len substring of the quote appearing in chunk
    for i in range(0, len(quote) - min_len + 1):
        if quote[i : i + min_len] in chunk_text:
            return True
    return False


@pytest.mark.live
def test_snippet_quality_aggregate_pass_rate():
    """At least 70% of fixtures must yield a snippet that overlaps the
    historically-accepted evidence_quote (or be a defensible 'no relevant content')."""
    from agents.tools.fetch import fetch_text, fetch_rendered_text
    from agents.tools.extract import extract_text
    from agents.tools.snippet_picker import pick_snippet

    fixtures = _load_fixtures()
    if not fixtures:
        pytest.skip("No fixtures present. Run evaluation/build_snippet_fixtures.py first.")

    results = []
    for fix in fixtures:
        # Live fetch the source URL
        fetched = fetch_text(fix["source_url"])
        if fetched.failure_mode or not fetched.content:
            fetched = fetch_rendered_text(fix["source_url"])
        if fetched.failure_mode or not fetched.content:
            results.append({"row": fix, "status": "fetch_failed", "match": None})
            continue
        # fetch_text returns already-cleaned text
        extracted = extract_text(fetched.content, url=fix["source_url"], is_html=False)
        chunks, _ = pick_snippet(
            query=fix["query"], url=fix["source_url"], page_text=extracted,
        )
        if not chunks:
            results.append({"row": fix, "status": "picker_empty", "match": False})
            continue
        overlap = any(_substring_overlap(fix["evidence_quote"], c.text) for c in chunks)
        results.append({"row": fix, "status": "picked", "match": overlap})

    # Aggregate: among picker-returned cases, at least 70% overlap.
    # Ignore fetch_failed cases (network reality, not picker quality).
    pickable = [r for r in results if r["status"] != "fetch_failed"]
    if not pickable:
        pytest.skip("All fixture URLs failed to fetch -- not a picker quality signal.")
    matches = sum(1 for r in pickable if r["match"])
    pass_rate = matches / len(pickable)

    # Print a summary for the test runner / dissertation
    print(f"\nSnippet-quality results: {matches}/{len(pickable)} = {pass_rate:.0%}")
    print(f"Fetch failures: {sum(1 for r in results if r['status'] == 'fetch_failed')}/{len(results)}")
    for r in results:
        q = r["row"]["question_id"]
        cc = r["row"]["country_code"]
        print(f"  {q}/{cc}: {r['status']} match={r['match']}")

    assert pass_rate >= 0.70, (
        f"Snippet quality below threshold: {matches}/{len(pickable)} = {pass_rate:.0%}. "
        f"The picker is failing to find passages the swarm previously accepted on these pages."
    )
