"""Layer 2: snippet-quality fixture test.

For each row in tests/fixtures/snippet_quality.jsonl (generated by
evaluation/build_snippet_fixtures.py), run the EXACT production fetch+extract
path (search_diy._fetch_and_clean: raw HTML -> trafilatura main content),
run the DIY snippet picker, and assert the returned chunks overlap the
historically-accepted evidence_quote. Aggregate pass rate must be >= 70%
across the pages that yielded extractable text.

Overlap is checked with the project's own normalisation (agents.tools.
substring.normalise), the same standard the Verifier uses to accept a quote.
A raw byte-for-byte comparison is too strict: page text and captured quotes
routinely differ in smart quotes, non-breaking spaces, and whitespace (see
agents/tools/substring.py), so a raw check under-reports real matches.

Marked @pytest.mark.live (network + Claude). Skip by default.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from agents.tools.substring import normalise

_FIXTURE = Path(__file__).parent / "fixtures" / "snippet_quality.jsonl"


def _load_fixtures():
    if not _FIXTURE.exists():
        return []
    return [json.loads(line) for line in _FIXTURE.read_text(encoding="utf-8").splitlines() if line.strip()]


def _normalised_overlap(quote: str, chunk_text: str, min_len: int = 30) -> bool:
    """True if a >=min_len window of the NORMALISED quote appears in the
    normalised chunk. Mirrors the Verifier's acceptance standard."""
    nq = normalise(quote)
    nc = normalise(chunk_text)
    if not nq:
        return False
    if len(nq) < min_len:
        return nq in nc
    return any(nq[i : i + min_len] in nc for i in range(0, len(nq) - min_len + 1))


@pytest.mark.live
def test_snippet_quality_aggregate_pass_rate():
    """At least 70% of pages that yield extractable text must produce a snippet
    that overlaps the historically-accepted evidence_quote."""
    from agents.tools.search_diy import _fetch_and_clean
    from agents.tools.snippet_picker import pick_snippet

    fixtures = _load_fixtures()
    if not fixtures:
        pytest.skip("No fixtures present. Run evaluation/build_snippet_fixtures.py first.")

    results = []
    for fix in fixtures:
        # Exact production path: raw HTML -> trafilatura main content.
        extracted = _fetch_and_clean(fix["source_url"])
        if not extracted:
            results.append({"row": fix, "status": "no_text", "match": None})
            continue
        chunks, _ = pick_snippet(
            query=fix["query"], url=fix["source_url"], page_text=extracted,
        )
        if not chunks:
            results.append({"row": fix, "status": "picker_empty", "match": False})
            continue
        overlap = any(_normalised_overlap(fix["evidence_quote"], c.text) for c in chunks)
        results.append({"row": fix, "status": "picked", "match": overlap})

    # Aggregate over pages that yielded text. no_text = fetch/extract failure
    # (network reality), excluded from the picker-quality denominator.
    pickable = [r for r in results if r["status"] != "no_text"]
    if not pickable:
        pytest.skip("No fixture URLs yielded extractable text -- not a picker quality signal.")
    matches = sum(1 for r in pickable if r["match"])
    pass_rate = matches / len(pickable)

    # Print a summary for the test runner / dissertation
    print(f"\nSnippet-quality results: {matches}/{len(pickable)} = {pass_rate:.0%}")
    print(f"No extractable text: {sum(1 for r in results if r['status'] == 'no_text')}/{len(results)}")
    for r in results:
        q = r["row"]["question_id"]
        cc = r["row"]["country_code"]
        print(f"  {q}/{cc}: {r['status']} match={r['match']}")

    assert pass_rate >= 0.70, (
        f"Snippet quality below threshold: {matches}/{len(pickable)} = {pass_rate:.0%}. "
        f"The picker is failing to find passages the swarm previously accepted on these pages."
    )
